### ISSUE TITLE
Bundle includes a copy of the JSX runtime

### ISSUE THREAD

**Issue by nstadigs** [sinasadjadi/mqtt-react-hook#1]
See topic.

Also, React should probably be a peerDependency instead of a dependency.

**Comment by nstadigs** [comment]
Great library btw. Thanks for sharing :)

**Comment by nstadigs** [comment]
Edited the topic. It was just the jsx runtime that was getting bundled.

**Comment by nstadigs** [comment]
Closing this until I know that this is the problem. I'm failing to run this with react 19.

**Comment by sinasadjadi** [comment]
Hi @nstadigs
Sorry for the late reply. I’ve been really busy lately.
Thanks for the feedback.
The issue has been fixed in this [commit](https://github.com/sinasadjadi/mqtt-react-hook/commit/bd93f5b95dc4ade53649d0744560d15048959f9f).

**Comment by nstadigs** [comment]
No worries! This is OSS. I expect nothing. Just wanted to let you know :)

Fix looks good! Thanks 🙏
